# -*- coding: utf-8 -*-
"""construcao_de_escalas_maiores_automático.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mj4oSdR8Tga8mmQtZLWOmvtURQSfQoTf

#### Construção de escalas maiores (automatizada em Python)
"""

notes = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
major_intervals = [2, 2, 1, 2, 2, 2, 1]

def build_scale(start_note, intervals):
    scale = [start_note]
    i = notes.index(start_note)

    for step in intervals:
      i = (i + step) % 12
      scale.append(notes[i])
    return scale

print(build_scale('G', major_intervals))

# G – A – B – C – D – E – F♯ – G

print(build_scale('D', major_intervals))

# D – E – F♯ – G – A – B – C♯ – D

print(build_scale('E', major_intervals))

# E – F♯ – G♯ – A – B – C♯ – D♯ – E